# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'football_records_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #222222;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectionFrame = QtWidgets.QFrame(self.centralwidget)
        self.selectionFrame.setGeometry(QtCore.QRect(0, 80, 331, 351))
        self.selectionFrame.setStyleSheet("background-color: #2b2b2b; border-radius: 8px;")
        self.selectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectionFrame.setObjectName("selectionFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.selectionFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.championshipLabel = QtWidgets.QLabel(self.selectionFrame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.championshipLabel.setFont(font)
        self.championshipLabel.setStyleSheet("color: #ffffff; font-size: 14px; font-weight: bold;")
        self.championshipLabel.setObjectName("championshipLabel")
        self.verticalLayout.addWidget(self.championshipLabel)
        self.championshipComboBox = QtWidgets.QComboBox(self.selectionFrame)
        self.championshipComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #444444;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /* სტანდარტული ჩამოსაშლელი ღილაკის სტილი */\n"
"    border: 0px; /* ან დატოვეთ default */\n"
"}\n"
"QComboBox::down-arrow {\n"
"    /* სტანდარტული ისრის სტილი */\n"
"    image: url(:/icons/down_arrow.png); /* თუ გაქვთ ასეთი ხატი, წინააღმდეგ შემთხვევაში წაშალეთ */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #3a3a3a; /* ჩამოსაშლელი სიის ფონი */\n"
"    border: 1px solid #555555; /* ჩამოსაშლელი სიის საზღვარი */\n"
"    selection-background-color: #007bff; /* არჩეული ელემენტის ფონი */\n"
"    selection-color: #ffffff; /* არჩეული ელემენტის ტექსტის ფერი */\n"
"    color: #ffffff; /* ჩვეულებრივი ელემენტის ტექსტის ფერი */\n"
"    outline: none; /* მოაშორეთ ფოკუსის ჩარჩო */\n"
"}")
        self.championshipComboBox.setObjectName("championshipComboBox")
        self.championshipComboBox.addItem("")
        self.championshipComboBox.addItem("")
        self.championshipComboBox.addItem("")
        self.championshipComboBox.addItem("")
        self.championshipComboBox.addItem("")
        self.verticalLayout.addWidget(self.championshipComboBox)
        self.positionLabel = QtWidgets.QLabel(self.selectionFrame)
        self.positionLabel.setStyleSheet("color: #ffffff; font-size: 14px; font-weight: bold;")
        self.positionLabel.setObjectName("positionLabel")
        self.verticalLayout.addWidget(self.positionLabel)
        self.positionComboBox = QtWidgets.QComboBox(self.selectionFrame)
        self.positionComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #444444;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /* სტანდარტული ჩამოსაშლელი ღილაკის სტილი */\n"
"    border: 0px; /* ან დატოვეთ default */\n"
"}\n"
"QComboBox::down-arrow {\n"
"    /* სტანდარტული ისრის სტილი */\n"
"    image: url(:/icons/down_arrow.png); /* თუ გაქვთ ასეთი ხატი, წინააღმდეგ შემთხვევაში წაშალეთ */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #3a3a3a; /* ჩამოსაშლელი სიის ფონი */\n"
"    border: 1px solid #555555; /* ჩამოსაშლელი სიის საზღვარი */\n"
"    selection-background-color: #007bff; /* არჩეული ელემენტის ფონი */\n"
"    selection-color: #ffffff; /* არჩეული ელემენტის ტექსტის ფერი */\n"
"    color: #ffffff; /* ჩვეულებრივი ელემენტის ტექსტის ფერი */\n"
"    outline: none; /* მოაშორეთ ფოკუსის ჩარჩო */\n"
"}")
        self.positionComboBox.setObjectName("positionComboBox")
        self.positionComboBox.addItem("")
        self.positionComboBox.addItem("")
        self.positionComboBox.addItem("")
        self.positionComboBox.addItem("")
        self.verticalLayout.addWidget(self.positionComboBox)
        self.recordTypeLabel_2 = QtWidgets.QLabel(self.selectionFrame)
        self.recordTypeLabel_2.setStyleSheet("color: #ffffff; font-size: 14px; font-weight: bold;")
        self.recordTypeLabel_2.setObjectName("recordTypeLabel_2")
        self.verticalLayout.addWidget(self.recordTypeLabel_2)
        self.recordTypeComboBox = QtWidgets.QComboBox(self.selectionFrame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.recordTypeComboBox.setFont(font)
        self.recordTypeComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #444444;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /* სტანდარტული ჩამოსაშლელი ღილაკის სტილი */\n"
"    border: 0px; /* ან დატოვეთ default */\n"
"}\n"
"QComboBox::down-arrow {\n"
"    /* სტანდარტული ისრის სტილი */\n"
"    image: url(:/icons/down_arrow.png); /* თუ გაქვთ ასეთი ხატი, წინააღმდეგ შემთხვევაში წაშალეთ */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #3a3a3a; /* ჩამოსაშლელი სიის ფონი */\n"
"    border: 1px solid #555555; /* ჩამოსაშლელი სიის საზღვარი */\n"
"    selection-background-color: #007bff; /* არჩეული ელემენტის ფონი */\n"
"    selection-color: #ffffff; /* არჩეული ელემენტის ტექსტის ფერი */\n"
"    color: #ffffff; /* ჩვეულებრივი ელემენტის ტექსტის ფერი */\n"
"    outline: none; /* მოაშორეთ ფოკუსის ჩარჩო */\n"
"}")
        self.recordTypeComboBox.setObjectName("recordTypeComboBox")
        self.recordTypeComboBox.addItem("")
        self.recordTypeComboBox.addItem("")
        self.recordTypeComboBox.addItem("")
        self.recordTypeComboBox.addItem("")
        self.recordTypeComboBox.addItem("")
        self.verticalLayout.addWidget(self.recordTypeComboBox)
        self.showRecordButton = QtWidgets.QPushButton(self.selectionFrame)
        self.showRecordButton.setStyleSheet("background-color: #4CAF50; color: white; border-radius: 5px; padding: 10px;\n"
"")
        self.showRecordButton.setObjectName("showRecordButton")
        self.verticalLayout.addWidget(self.showRecordButton)
        self.displayFrame = QtWidgets.QFrame(self.centralwidget)
        self.displayFrame.setGeometry(QtCore.QRect(330, 0, 471, 541))
        self.displayFrame.setStyleSheet(" #3a3a3a; border-radius: 8px;")
        self.displayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.displayFrame.setObjectName("displayFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.displayFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.recordTitleLabel = QtWidgets.QLabel(self.displayFrame)
        self.recordTitleLabel.setStyleSheet("color: #ffffff; font-size: 18px; font-weight: bold;")
        self.recordTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recordTitleLabel.setObjectName("recordTitleLabel")
        self.verticalLayout_2.addWidget(self.recordTitleLabel)
        self.recordDisplayLabel = QtWidgets.QLabel(self.displayFrame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.recordDisplayLabel.setFont(font)
        self.recordDisplayLabel.setStyleSheet("color: #cccccc; font-size: 16px; word-wrap: true;")
        self.recordDisplayLabel.setWordWrap(True)
        self.recordDisplayLabel.setObjectName("recordDisplayLabel")
        self.verticalLayout_2.addWidget(self.recordDisplayLabel)
        self.recordDescriptionLabel = QtWidgets.QLabel(self.displayFrame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.recordDescriptionLabel.setFont(font)
        self.recordDescriptionLabel.setStyleSheet("color: #aaaaaa; font-size: 14px; word-wrap: true;")
        self.recordDescriptionLabel.setWordWrap(True)
        self.recordDescriptionLabel.setObjectName("recordDescriptionLabel")
        self.verticalLayout_2.addWidget(self.recordDescriptionLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: #333333; color: #ffffff;")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "საფეხბურთო რეკორდები"))
        self.championshipLabel.setText(_translate("MainWindow", "ჩემპიონატი"))
        self.championshipComboBox.setItemText(0, _translate("MainWindow", "ინგლისის პრემიერ ლიგა"))
        self.championshipComboBox.setItemText(1, _translate("MainWindow", "ესპანეთის ლა ლიგა"))
        self.championshipComboBox.setItemText(2, _translate("MainWindow", "იტალიის სერია ა"))
        self.championshipComboBox.setItemText(3, _translate("MainWindow", "საფრანგეთის ლიგა 1"))
        self.championshipComboBox.setItemText(4, _translate("MainWindow", "ჩემპიონთა ლიგა"))
        self.positionLabel.setText(_translate("MainWindow", "პოზიცია"))
        self.positionComboBox.setItemText(0, _translate("MainWindow", "თავდამსხმელი"))
        self.positionComboBox.setItemText(1, _translate("MainWindow", "ნახევარმცველი"))
        self.positionComboBox.setItemText(2, _translate("MainWindow", "მცველი"))
        self.positionComboBox.setItemText(3, _translate("MainWindow", "მეკარე"))
        self.recordTypeLabel_2.setText(_translate("MainWindow", "რეკორდის ტიპი"))
        self.recordTypeComboBox.setItemText(0, _translate("MainWindow", "გატანილი გოლები"))
        self.recordTypeComboBox.setItemText(1, _translate("MainWindow", "საგოლე გადაცემა"))
        self.recordTypeComboBox.setItemText(2, _translate("MainWindow", "ყვითელი ბარათი"))
        self.recordTypeComboBox.setItemText(3, _translate("MainWindow", "წითელი ბარათი"))
        self.recordTypeComboBox.setItemText(4, _translate("MainWindow", "მშრალი კარი"))
        self.showRecordButton.setText(_translate("MainWindow", "რეკორდის ჩვენება"))
        self.recordTitleLabel.setText(_translate("MainWindow", "საფეხბურთო რეკორდი"))
        self.recordDisplayLabel.setText(_translate("MainWindow", "აირჩიეთ ჩემპიონატი, პოზიცია და რეკორდის ტიპი..."))
        self.recordDescriptionLabel.setText(_translate("MainWindow", "ინფორმაცია აქ გამოჩნდება."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
